# Generated by Django 3.0.6 on 2020-11-02 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=30, verbose_name='标题')),
                ('subject', models.CharField(max_length=20, verbose_name='主题')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '卷子',
                'verbose_name_plural': '卷子',
                'db_table': 'Papers',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='题目')),
                ('answer', models.TextField(verbose_name='答案')),
                ('right_answer', models.TextField(verbose_name='答案')),
                ('score', models.IntegerField(default=1, verbose_name='分数')),
                ('paper_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Papers')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'question',
            },
        ),
    ]
